lio_3d_node:
  ros__parameters:
    lidar_type: "rfans"
    use_as_localizer: true
    # map_cloud_dir: "/tmp/pslam_data/"
    map_cloud_dir: "/home/takumi/ros2_ws/src/plain_slam_ros2/maps/sim/"
    param_files_dir: "" # LIO parameters must be located under plain_slam_ros2/config/

    pointcloud_topic: "/surestar_points"
    imu_topic: "/imu/data"

    imu_pose_topic: "/pslam/imu_pose"
    imu_odom_topic: "/pslam/imu_odom"
    lio_map_cloud_topic: "/pslam/lio_map_cloud"
    aligned_scan_cloud_topic: "/pslam/aligned_scan_cloud"
    deskewed_scan_cloud_topic: "/pslam/deskewed_scan_cloud"

    odom_frame: "odom"
    imu_frame: "imu"
