initial_pose:
  translation: [0.0, 0.0, 0.0]
  rotation_matrix: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

extrinsics:
  imu_to_lidar:
    # tuned for orne_box_3d_lidar_rfans.urdf.xacro
    # imu   : xyz = [ 0.23, 0.0, 0.27] in base_link
    # lidar : xyz = [-0.12, 0.0, 0.60] in base_link
    # imu_to_lidar = lidar - imu
    translation: [-0.35, 0.0, 0.33]
    rotation_matrix: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    # translation: [-0.006253, 0.011775, 0.028535] # outster os1
    # rotation_matrix: [-1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0] # outster os1

imu_params:
  # acc_scale: 9.79 # livox
  acc_scale: 1.0

keyframe:
  distance_th: 0.5
  angle_th: 1000.0 # degree
  min_active_points_rate: 0.75

scan_cloud_preprocess:
  clip_range: 0.5
  filter_size: 0.05

normal_map:
  num_keyframes: 50
  filter_size: 0.04
  num_normal_points: 8
  normal_eigen_val_thresh: 0.08

estimator:
  use_loose_coupling: false
  huber_delta: 0.1
  num_max_iteration: 20
  num_max_matching_points: 100000
  max_correspondence_dist: 1.0
  convergence_th: 0.05
