preprocess:
  accumulation_cycle: 3
  scan_cloud_filter_size: 0.02

keyframe:
  distance_th: 2.5
  angle_th: 20.0
  min_local_map_matching_rate: 0.75

loop_closure:
  num_loop_candidates: 10
  loop_detection_distance_thresh: 30.0
  loop_detection_height_thresh: 2.0
  error_average_th: 0.3
  active_points_rate_th: 0.72
  gicp_max_iteration: 50
  gicp_epsilon: 0.001
  gicp_max_correspondence_dist: 1.0
  gicp_huber_delta: 0.2

pose_graph:
  huber_delta: 0.05
